### PR TITLE
feat: 在某个服务内弹出公告 #6510

### PR DESCRIPTION
**Pull request by yjieliang**
feat: 在某个服务内弹出公告 #6510

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/bk-ci?pullRequest=6634) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/bk-ci?pullRequest=6634) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/bk-ci?pullRequest=6634) it.</sub>

**Review by carlyin0801 — APPROVED** [review]
ok

**Review by carlyin0801 — APPROVED** [review]
ok

**Review by carlyin0801 — APPROVED** [review]
ok

**Review by carlyin0801 — APPROVED** [review]
ok

**Review by irwinsun — APPROVED** [review]

**Pull request merged**
